task:
  title: Draw bounding boxes around the strip
dataset:
  directory: dataset/object_detection/
  data_type: images
  judgements_file: outputs/object_detection/labels.csv
label:
  type: object_detection
  classes:
    - box
model:
  directory: outputs/object_detection/models/
user: chris
